# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import ui.resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1024, 571))
        self.stackedWidget.setObjectName("stackedWidget")
        self.controllerPage = QtWidgets.QWidget()
        self.controllerPage.setObjectName("controllerPage")
        self.timerFrame = QtWidgets.QFrame(self.controllerPage)
        self.timerFrame.setGeometry(QtCore.QRect(10, 390, 331, 171))
        self.timerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.timerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.timerFrame.setObjectName("timerFrame")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.timerFrame)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(0, 0, 331, 171))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout7.setObjectName("horizontalLayout7")
        self.timerLCD = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timerLCD.sizePolicy().hasHeightForWidth())
        self.timerLCD.setSizePolicy(sizePolicy)
        self.timerLCD.setMinimumSize(QtCore.QSize(85, 85))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.timerLCD.setFont(font)
        self.timerLCD.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.timerLCD.setFrameShadow(QtWidgets.QFrame.Plain)
        self.timerLCD.setDigitCount(5)
        self.timerLCD.setProperty("value", 0.0)
        self.timerLCD.setObjectName("timerLCD")
        self.horizontalLayout7.addWidget(self.timerLCD)
        self.horizontalLayout8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout8.setObjectName("horizontalLayout8")
        self.verticalLayout1 = QtWidgets.QVBoxLayout()
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.increaseTimerButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.increaseTimerButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.increaseTimerButton.setIcon(icon)
        self.increaseTimerButton.setIconSize(QtCore.QSize(56, 56))
        self.increaseTimerButton.setAutoDefault(False)
        self.increaseTimerButton.setDefault(False)
        self.increaseTimerButton.setFlat(True)
        self.increaseTimerButton.setObjectName("increaseTimerButton")
        self.verticalLayout1.addWidget(self.increaseTimerButton)
        self.decreaseTimerButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.decreaseTimerButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.decreaseTimerButton.setIcon(icon1)
        self.decreaseTimerButton.setIconSize(QtCore.QSize(56, 56))
        self.decreaseTimerButton.setAutoDefault(False)
        self.decreaseTimerButton.setDefault(False)
        self.decreaseTimerButton.setFlat(True)
        self.decreaseTimerButton.setObjectName("decreaseTimerButton")
        self.verticalLayout1.addWidget(self.decreaseTimerButton)
        self.horizontalLayout8.addLayout(self.verticalLayout1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.startTimerButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.startTimerButton.setFont(font)
        self.startTimerButton.setFlat(True)
        self.startTimerButton.setObjectName("startTimerButton")
        self.verticalLayout.addWidget(self.startTimerButton)
        self.stopTimerButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.stopTimerButton.setFont(font)
        self.stopTimerButton.setAutoDefault(False)
        self.stopTimerButton.setFlat(True)
        self.stopTimerButton.setObjectName("stopTimerButton")
        self.verticalLayout.addWidget(self.stopTimerButton)
        self.resetTimerButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.resetTimerButton.setFont(font)
        self.resetTimerButton.setFlat(True)
        self.resetTimerButton.setObjectName("resetTimerButton")
        self.verticalLayout.addWidget(self.resetTimerButton)
        self.horizontalLayout8.addLayout(self.verticalLayout)
        self.horizontalLayout7.addLayout(self.horizontalLayout8)
        self.burnerLabel = QtWidgets.QLabel(self.controllerPage)
        self.burnerLabel.setGeometry(QtCore.QRect(920, 380, 54, 17))
        self.burnerLabel.setText("")
        self.burnerLabel.setObjectName("burnerLabel")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.controllerPage)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(540, 290, 86, 111))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout3.setSpacing(0)
        self.verticalLayout3.setObjectName("verticalLayout3")
        self.intLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.intLabel.setFont(font)
        self.intLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.intLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.intLabel.setObjectName("intLabel")
        self.verticalLayout3.addWidget(self.intLabel)
        self.internalOpeningButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.internalOpeningButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resources/openingOpen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/resources/openingClose.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.internalOpeningButton.setIcon(icon2)
        self.internalOpeningButton.setIconSize(QtCore.QSize(64, 64))
        self.internalOpeningButton.setCheckable(True)
        self.internalOpeningButton.setAutoDefault(False)
        self.internalOpeningButton.setDefault(False)
        self.internalOpeningButton.setFlat(True)
        self.internalOpeningButton.setObjectName("internalOpeningButton")
        self.verticalLayout3.addWidget(self.internalOpeningButton)
        self.thermostatFrame = QtWidgets.QFrame(self.controllerPage)
        self.thermostatFrame.setGeometry(QtCore.QRect(540, 420, 471, 141))
        self.thermostatFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.thermostatFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.thermostatFrame.setObjectName("thermostatFrame")
        self.thermostatLabel = QtWidgets.QLabel(self.thermostatFrame)
        self.thermostatLabel.setGeometry(QtCore.QRect(10, 0, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.thermostatLabel.setFont(font)
        self.thermostatLabel.setWordWrap(False)
        self.thermostatLabel.setObjectName("thermostatLabel")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.thermostatFrame)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 40, 451, 91))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout5.setObjectName("horizontalLayout5")
        self.decrementThermostatButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.decrementThermostatButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resources/thermostatDown.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.decrementThermostatButton.setIcon(icon3)
        self.decrementThermostatButton.setIconSize(QtCore.QSize(64, 64))
        self.decrementThermostatButton.setAutoRepeat(True)
        self.decrementThermostatButton.setAutoRepeatDelay(100)
        self.decrementThermostatButton.setAutoRepeatInterval(400)
        self.decrementThermostatButton.setAutoDefault(False)
        self.decrementThermostatButton.setDefault(False)
        self.decrementThermostatButton.setFlat(True)
        self.decrementThermostatButton.setObjectName("decrementThermostatButton")
        self.horizontalLayout5.addWidget(self.decrementThermostatButton)
        self.horizontalSlider = QtWidgets.QSlider(self.horizontalLayoutWidget_5)
        self.horizontalSlider.setMinimum(100)
        self.horizontalSlider.setMaximum(550)
        self.horizontalSlider.setSingleStep(5)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setTickInterval(50)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout5.addWidget(self.horizontalSlider)
        self.incrementThermostatButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.incrementThermostatButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/resources/thermostatUp.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.incrementThermostatButton.setIcon(icon4)
        self.incrementThermostatButton.setIconSize(QtCore.QSize(64, 64))
        self.incrementThermostatButton.setAutoRepeat(True)
        self.incrementThermostatButton.setAutoRepeatDelay(100)
        self.incrementThermostatButton.setAutoRepeatInterval(400)
        self.incrementThermostatButton.setAutoDefault(False)
        self.incrementThermostatButton.setDefault(False)
        self.incrementThermostatButton.setFlat(True)
        self.incrementThermostatButton.setObjectName("incrementThermostatButton")
        self.horizontalLayout5.addWidget(self.incrementThermostatButton)
        self.thermostatLCD = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thermostatLCD.sizePolicy().hasHeightForWidth())
        self.thermostatLCD.setSizePolicy(sizePolicy)
        self.thermostatLCD.setMinimumSize(QtCore.QSize(100, 0))
        self.thermostatLCD.setMaximumSize(QtCore.QSize(16777215, 60))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 1, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 1, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 157, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.thermostatLCD.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.thermostatLCD.setFont(font)
        self.thermostatLCD.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.thermostatLCD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.thermostatLCD.setDigitCount(3)
        self.thermostatLCD.setProperty("value", 100.0)
        self.thermostatLCD.setObjectName("thermostatLCD")
        self.horizontalLayout5.addWidget(self.thermostatLCD)
        self.thermostatDegreeLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(34)
        font.setBold(False)
        font.setWeight(50)
        self.thermostatDegreeLabel.setFont(font)
        self.thermostatDegreeLabel.setWordWrap(False)
        self.thermostatDegreeLabel.setObjectName("thermostatDegreeLabel")
        self.horizontalLayout5.addWidget(self.thermostatDegreeLabel)
        self.burnerValveLabel = QtWidgets.QLabel(self.controllerPage)
        self.burnerValveLabel.setEnabled(True)
        self.burnerValveLabel.setGeometry(QtCore.QRect(810, 350, 41, 41))
        self.burnerValveLabel.setText("")
        self.burnerValveLabel.setPixmap(QtGui.QPixmap(":/resources/burnerValveFlame.png"))
        self.burnerValveLabel.setScaledContents(True)
        self.burnerValveLabel.setObjectName("burnerValveLabel")
        self.line_3 = QtWidgets.QFrame(self.controllerPage)
        self.line_3.setGeometry(QtCore.QRect(530, 190, 491, 20))
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.controllerPage)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 100, 501, 91))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.temperatureFloorLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.temperatureFloorLabel.setFont(font)
        self.temperatureFloorLabel.setWordWrap(False)
        self.temperatureFloorLabel.setObjectName("temperatureFloorLabel")
        self.horizontalLayout2.addWidget(self.temperatureFloorLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout2.addItem(spacerItem)
        self.floorLCD = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.floorLCD.sizePolicy().hasHeightForWidth())
        self.floorLCD.setSizePolicy(sizePolicy)
        self.floorLCD.setMinimumSize(QtCore.QSize(85, 85))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.floorLCD.setFont(font)
        self.floorLCD.setFrameShape(QtWidgets.QFrame.Box)
        self.floorLCD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.floorLCD.setDigitCount(3)
        self.floorLCD.setObjectName("floorLCD")
        self.horizontalLayout2.addWidget(self.floorLCD)
        self.degreeLabel2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.degreeLabel2.setFont(font)
        self.degreeLabel2.setWordWrap(False)
        self.degreeLabel2.setObjectName("degreeLabel2")
        self.horizontalLayout2.addWidget(self.degreeLabel2)
        self.lightButton = QtWidgets.QPushButton(self.controllerPage)
        self.lightButton.setGeometry(QtCore.QRect(540, 210, 76, 70))
        self.lightButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/resources/lightOff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/resources/lightOn.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.lightButton.setIcon(icon5)
        self.lightButton.setIconSize(QtCore.QSize(64, 64))
        self.lightButton.setCheckable(True)
        self.lightButton.setAutoDefault(False)
        self.lightButton.setDefault(False)
        self.lightButton.setFlat(True)
        self.lightButton.setObjectName("lightButton")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.controllerPage)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 280, 501, 91))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout4.setObjectName("horizontalLayout4")
        self.temperatureFumesLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.temperatureFumesLabel.setFont(font)
        self.temperatureFumesLabel.setWordWrap(False)
        self.temperatureFumesLabel.setObjectName("temperatureFumesLabel")
        self.horizontalLayout4.addWidget(self.temperatureFumesLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout4.addItem(spacerItem1)
        self.fumesLCD = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fumesLCD.sizePolicy().hasHeightForWidth())
        self.fumesLCD.setSizePolicy(sizePolicy)
        self.fumesLCD.setMinimumSize(QtCore.QSize(85, 85))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fumesLCD.setFont(font)
        self.fumesLCD.setFrameShape(QtWidgets.QFrame.Box)
        self.fumesLCD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fumesLCD.setDigitCount(3)
        self.fumesLCD.setObjectName("fumesLCD")
        self.horizontalLayout4.addWidget(self.fumesLCD)
        self.degreeLabel4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.degreeLabel4.setFont(font)
        self.degreeLabel4.setWordWrap(False)
        self.degreeLabel4.setObjectName("degreeLabel4")
        self.horizontalLayout4.addWidget(self.degreeLabel4)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.controllerPage)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(630, 290, 86, 111))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout4.setSpacing(0)
        self.verticalLayout4.setObjectName("verticalLayout4")
        self.estLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.estLabel.setFont(font)
        self.estLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.estLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.estLabel.setObjectName("estLabel")
        self.verticalLayout4.addWidget(self.estLabel)
        self.externalOpeningButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.externalOpeningButton.setText("")
        self.externalOpeningButton.setIcon(icon2)
        self.externalOpeningButton.setIconSize(QtCore.QSize(64, 64))
        self.externalOpeningButton.setCheckable(True)
        self.externalOpeningButton.setAutoDefault(False)
        self.externalOpeningButton.setDefault(False)
        self.externalOpeningButton.setFlat(True)
        self.externalOpeningButton.setObjectName("externalOpeningButton")
        self.verticalLayout4.addWidget(self.externalOpeningButton)
        self.fanButton = QtWidgets.QPushButton(self.controllerPage)
        self.fanButton.setGeometry(QtCore.QRect(720, 210, 76, 70))
        self.fanButton.setText("")
        self.fanButton.setIconSize(QtCore.QSize(76, 76))
        self.fanButton.setCheckable(False)
        self.fanButton.setAutoDefault(False)
        self.fanButton.setDefault(False)
        self.fanButton.setFlat(True)
        self.fanButton.setObjectName("fanButton")
        self.burnerButton = QtWidgets.QPushButton(self.controllerPage)
        self.burnerButton.setGeometry(QtCore.QRect(390, 490, 86, 80))
        self.burnerButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/resources/OnOff.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.burnerButton.setIcon(icon6)
        self.burnerButton.setIconSize(QtCore.QSize(64, 64))
        self.burnerButton.setAutoDefault(False)
        self.burnerButton.setDefault(False)
        self.burnerButton.setFlat(True)
        self.burnerButton.setObjectName("burnerButton")
        self.steamButton = QtWidgets.QPushButton(self.controllerPage)
        self.steamButton.setGeometry(QtCore.QRect(630, 210, 76, 70))
        self.steamButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/resources/steam.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.steamButton.setIcon(icon7)
        self.steamButton.setIconSize(QtCore.QSize(76, 76))
        self.steamButton.setCheckable(False)
        self.steamButton.setAutoDefault(False)
        self.steamButton.setDefault(False)
        self.steamButton.setFlat(True)
        self.steamButton.setObjectName("steamButton")
        self.line_2 = QtWidgets.QFrame(self.controllerPage)
        self.line_2.setGeometry(QtCore.QRect(520, 10, 16, 551))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.line_2.setFont(font)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.controllerPage)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(540, 100, 471, 91))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout9.setObjectName("horizontalLayout9")
        self.gasLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.gasLabel.setFont(font)
        self.gasLabel.setWordWrap(False)
        self.gasLabel.setObjectName("gasLabel")
        self.horizontalLayout9.addWidget(self.gasLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout9.addItem(spacerItem2)
        self.gasLCD = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gasLCD.sizePolicy().hasHeightForWidth())
        self.gasLCD.setSizePolicy(sizePolicy)
        self.gasLCD.setMinimumSize(QtCore.QSize(85, 85))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.gasLCD.setFont(font)
        self.gasLCD.setFrameShape(QtWidgets.QFrame.Box)
        self.gasLCD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gasLCD.setDigitCount(4)
        self.gasLCD.setObjectName("gasLCD")
        self.horizontalLayout9.addWidget(self.gasLCD)
        self.PaLabel2 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.PaLabel2.setFont(font)
        self.PaLabel2.setWordWrap(False)
        self.PaLabel2.setObjectName("PaLabel2")
        self.horizontalLayout9.addWidget(self.PaLabel2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.controllerPage)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 501, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.temperatureOvenLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.temperatureOvenLabel.setFont(font)
        self.temperatureOvenLabel.setWordWrap(False)
        self.temperatureOvenLabel.setObjectName("temperatureOvenLabel")
        self.horizontalLayout1.addWidget(self.temperatureOvenLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout1.addItem(spacerItem3)
        self.ovenLCD = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ovenLCD.sizePolicy().hasHeightForWidth())
        self.ovenLCD.setSizePolicy(sizePolicy)
        self.ovenLCD.setMinimumSize(QtCore.QSize(85, 85))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ovenLCD.setFont(font)
        self.ovenLCD.setFrameShape(QtWidgets.QFrame.Box)
        self.ovenLCD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ovenLCD.setDigitCount(3)
        self.ovenLCD.setObjectName("ovenLCD")
        self.horizontalLayout1.addWidget(self.ovenLCD)
        self.degreeLabel1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.degreeLabel1.setFont(font)
        self.degreeLabel1.setWordWrap(False)
        self.degreeLabel1.setObjectName("degreeLabel1")
        self.horizontalLayout1.addWidget(self.degreeLabel1)
        self.line = QtWidgets.QFrame(self.controllerPage)
        self.line.setGeometry(QtCore.QRect(7, 370, 521, 20))
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.controllerPage)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(540, 10, 471, 91))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout6.setObjectName("horizontalLayout6")
        self.pressionLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pressionLabel.setFont(font)
        self.pressionLabel.setWordWrap(False)
        self.pressionLabel.setObjectName("pressionLabel")
        self.horizontalLayout6.addWidget(self.pressionLabel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout6.addItem(spacerItem4)
        self.pressionLCD = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pressionLCD.sizePolicy().hasHeightForWidth())
        self.pressionLCD.setSizePolicy(sizePolicy)
        self.pressionLCD.setMinimumSize(QtCore.QSize(85, 85))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pressionLCD.setFont(font)
        self.pressionLCD.setFrameShape(QtWidgets.QFrame.Box)
        self.pressionLCD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pressionLCD.setDigitCount(4)
        self.pressionLCD.setObjectName("pressionLCD")
        self.horizontalLayout6.addWidget(self.pressionLCD)
        self.PaLabel1 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.PaLabel1.setFont(font)
        self.PaLabel1.setWordWrap(False)
        self.PaLabel1.setObjectName("PaLabel1")
        self.horizontalLayout6.addWidget(self.PaLabel1)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.controllerPage)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 190, 501, 91))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout3.setObjectName("horizontalLayout3")
        self.temperaturePufferLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.temperaturePufferLabel.setFont(font)
        self.temperaturePufferLabel.setWordWrap(False)
        self.temperaturePufferLabel.setObjectName("temperaturePufferLabel")
        self.horizontalLayout3.addWidget(self.temperaturePufferLabel)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout3.addItem(spacerItem5)
        self.pufferLCD = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pufferLCD.sizePolicy().hasHeightForWidth())
        self.pufferLCD.setSizePolicy(sizePolicy)
        self.pufferLCD.setMinimumSize(QtCore.QSize(85, 85))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pufferLCD.setFont(font)
        self.pufferLCD.setFrameShape(QtWidgets.QFrame.Box)
        self.pufferLCD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pufferLCD.setDigitCount(3)
        self.pufferLCD.setObjectName("pufferLCD")
        self.horizontalLayout3.addWidget(self.pufferLCD)
        self.degreeLabel3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.degreeLabel3.setFont(font)
        self.degreeLabel3.setWordWrap(False)
        self.degreeLabel3.setObjectName("degreeLabel3")
        self.horizontalLayout3.addWidget(self.degreeLabel3)
        self.burnerValveButton = QtWidgets.QPushButton(self.controllerPage)
        self.burnerValveButton.setGeometry(QtCore.QRect(720, 330, 76, 70))
        self.burnerValveButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/resources/burnerValveOff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/resources/burnerValveOn.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.burnerValveButton.setIcon(icon8)
        self.burnerValveButton.setIconSize(QtCore.QSize(70, 70))
        self.burnerValveButton.setCheckable(True)
        self.burnerValveButton.setAutoDefault(False)
        self.burnerValveButton.setDefault(False)
        self.burnerValveButton.setFlat(True)
        self.burnerValveButton.setObjectName("burnerValveButton")
        self.controller_settingsButton = QtWidgets.QPushButton(self.controllerPage)
        self.controller_settingsButton.setGeometry(QtCore.QRect(350, 390, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.controller_settingsButton.setFont(font)
        self.controller_settingsButton.setFlat(False)
        self.controller_settingsButton.setObjectName("controller_settingsButton")
        self.controller_chartsButton = QtWidgets.QPushButton(self.controllerPage)
        self.controller_chartsButton.setGeometry(QtCore.QRect(350, 440, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.controller_chartsButton.setFont(font)
        self.controller_chartsButton.setFlat(False)
        self.controller_chartsButton.setObjectName("controller_chartsButton")
        self.stackedWidget.addWidget(self.controllerPage)
        self.chartsPage = QtWidgets.QWidget()
        self.chartsPage.setObjectName("chartsPage")
        self.charts_controllerButton = QtWidgets.QPushButton(self.chartsPage)
        self.charts_controllerButton.setGeometry(QtCore.QRect(20, 80, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.charts_controllerButton.setFont(font)
        self.charts_controllerButton.setFlat(False)
        self.charts_controllerButton.setObjectName("charts_controllerButton")
        self.charts_settingsButton = QtWidgets.QPushButton(self.chartsPage)
        self.charts_settingsButton.setGeometry(QtCore.QRect(20, 130, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.charts_settingsButton.setFont(font)
        self.charts_settingsButton.setFlat(False)
        self.charts_settingsButton.setObjectName("charts_settingsButton")
        self.chartsLabel = QtWidgets.QLabel(self.chartsPage)
        self.chartsLabel.setGeometry(QtCore.QRect(20, 30, 651, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.chartsLabel.setFont(font)
        self.chartsLabel.setObjectName("chartsLabel")
        self.stackedWidget.addWidget(self.chartsPage)
        self.settingsPage = QtWidgets.QWidget()
        self.settingsPage.setObjectName("settingsPage")
        self.alexaButton = QtWidgets.QPushButton(self.settingsPage)
        self.alexaButton.setGeometry(QtCore.QRect(60, 190, 76, 70))
        self.alexaButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/resources/alexaOff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":/resources/alexaOn.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.alexaButton.setIcon(icon9)
        self.alexaButton.setIconSize(QtCore.QSize(64, 64))
        self.alexaButton.setCheckable(True)
        self.alexaButton.setAutoDefault(False)
        self.alexaButton.setDefault(False)
        self.alexaButton.setFlat(True)
        self.alexaButton.setObjectName("alexaButton")
        self.quitButton = QtWidgets.QPushButton(self.settingsPage)
        self.quitButton.setGeometry(QtCore.QRect(200, 80, 91, 81))
        self.quitButton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/resources/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.quitButton.setIcon(icon10)
        self.quitButton.setIconSize(QtCore.QSize(100, 100))
        self.quitButton.setCheckable(False)
        self.quitButton.setAutoDefault(False)
        self.quitButton.setDefault(False)
        self.quitButton.setFlat(True)
        self.quitButton.setObjectName("quitButton")
        self.settings_chartsButton = QtWidgets.QPushButton(self.settingsPage)
        self.settings_chartsButton.setGeometry(QtCore.QRect(20, 130, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.settings_chartsButton.setFont(font)
        self.settings_chartsButton.setFlat(False)
        self.settings_chartsButton.setObjectName("settings_chartsButton")
        self.settings_controllerButton = QtWidgets.QPushButton(self.settingsPage)
        self.settings_controllerButton.setGeometry(QtCore.QRect(20, 80, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.settings_controllerButton.setFont(font)
        self.settings_controllerButton.setFlat(False)
        self.settings_controllerButton.setObjectName("settings_controllerButton")
        self.label = QtWidgets.QLabel(self.settingsPage)
        self.label.setGeometry(QtCore.QRect(20, 30, 811, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.settingsPage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.horizontalSlider.valueChanged['int'].connect(self.thermostatLCD.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gestione Forno"))
        self.startTimerButton.setText(_translate("MainWindow", "Avvia"))
        self.stopTimerButton.setText(_translate("MainWindow", "Ferma"))
        self.resetTimerButton.setText(_translate("MainWindow", "Reset"))
        self.intLabel.setText(_translate("MainWindow", "INT"))
        self.thermostatLabel.setText(_translate("MainWindow", "Imposta temperatura"))
        self.thermostatDegreeLabel.setText(_translate("MainWindow", "°C"))
        self.temperatureFloorLabel.setText(_translate("MainWindow", "Temperatura platea"))
        self.degreeLabel2.setText(_translate("MainWindow", "°C"))
        self.temperatureFumesLabel.setText(_translate("MainWindow", "Temperatura u. fumi"))
        self.degreeLabel4.setText(_translate("MainWindow", "°C"))
        self.estLabel.setText(_translate("MainWindow", "EST"))
        self.gasLabel.setText(_translate("MainWindow", "Pressione gas"))
        self.PaLabel2.setText(_translate("MainWindow", "Pa"))
        self.temperatureOvenLabel.setText(_translate("MainWindow", "Temperatura forno"))
        self.degreeLabel1.setText(_translate("MainWindow", "°C"))
        self.pressionLabel.setText(_translate("MainWindow", "Pressione forno"))
        self.PaLabel1.setText(_translate("MainWindow", "Pa"))
        self.temperaturePufferLabel.setText(_translate("MainWindow", "Temperatura puffer"))
        self.degreeLabel3.setText(_translate("MainWindow", "°C"))
        self.controller_settingsButton.setText(_translate("MainWindow", "Impostazioni"))
        self.controller_chartsButton.setText(_translate("MainWindow", "Grafici"))
        self.charts_controllerButton.setText(_translate("MainWindow", "Controller"))
        self.charts_settingsButton.setText(_translate("MainWindow", "Impostazioni"))
        self.chartsLabel.setText(_translate("MainWindow", "IN QUESTA SEZIONE SARANNO MOSTRATI I GRAFICI DI ANDAMENTO."))
        self.settings_chartsButton.setText(_translate("MainWindow", "Grafici"))
        self.settings_controllerButton.setText(_translate("MainWindow", "Controller"))
        self.label.setText(_translate("MainWindow", "IN QUESTA SEZIONE PUOI CHIUDERE L\'APPLICAZIONE O TORNARE ALLE ALTRE VISTE."))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

