# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import ui.resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1024, 571))
        self.stackedWidget.setObjectName("stackedWidget")
        self.controllerPage = QtWidgets.QWidget()
        self.controllerPage.setObjectName("controllerPage")
        self.timerFrame = QtWidgets.QFrame(self.controllerPage)
        self.timerFrame.setGeometry(QtCore.QRect(10, 390, 391, 171))
        self.timerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.timerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.timerFrame.setObjectName("timerFrame")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.timerFrame)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 10, 371, 151))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout7.setObjectName("horizontalLayout7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.startTimerButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startTimerButton.sizePolicy().hasHeightForWidth())
        self.startTimerButton.setSizePolicy(sizePolicy)
        self.startTimerButton.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.startTimerButton.setFont(font)
        self.startTimerButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.startTimerButton.setFlat(False)
        self.startTimerButton.setObjectName("startTimerButton")
        self.verticalLayout.addWidget(self.startTimerButton)
        self.stopTimerButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopTimerButton.sizePolicy().hasHeightForWidth())
        self.stopTimerButton.setSizePolicy(sizePolicy)
        self.stopTimerButton.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.stopTimerButton.setFont(font)
        self.stopTimerButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stopTimerButton.setAutoDefault(False)
        self.stopTimerButton.setFlat(False)
        self.stopTimerButton.setObjectName("stopTimerButton")
        self.verticalLayout.addWidget(self.stopTimerButton)
        self.resetTimerButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetTimerButton.sizePolicy().hasHeightForWidth())
        self.resetTimerButton.setSizePolicy(sizePolicy)
        self.resetTimerButton.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.resetTimerButton.setFont(font)
        self.resetTimerButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.resetTimerButton.setFlat(False)
        self.resetTimerButton.setObjectName("resetTimerButton")
        self.verticalLayout.addWidget(self.resetTimerButton)
        self.horizontalLayout7.addLayout(self.verticalLayout)
        self.timerLCD = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timerLCD.sizePolicy().hasHeightForWidth())
        self.timerLCD.setSizePolicy(sizePolicy)
        self.timerLCD.setMinimumSize(QtCore.QSize(85, 85))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.timerLCD.setFont(font)
        self.timerLCD.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.timerLCD.setFrameShadow(QtWidgets.QFrame.Plain)
        self.timerLCD.setDigitCount(5)
        self.timerLCD.setProperty("value", 0.0)
        self.timerLCD.setObjectName("timerLCD")
        self.horizontalLayout7.addWidget(self.timerLCD)
        self.verticalLayout1 = QtWidgets.QVBoxLayout()
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.increaseTimerButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.increaseTimerButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.increaseTimerButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.increaseTimerButton.setIcon(icon)
        self.increaseTimerButton.setIconSize(QtCore.QSize(56, 56))
        self.increaseTimerButton.setAutoDefault(False)
        self.increaseTimerButton.setDefault(False)
        self.increaseTimerButton.setFlat(True)
        self.increaseTimerButton.setObjectName("increaseTimerButton")
        self.verticalLayout1.addWidget(self.increaseTimerButton)
        self.decreaseTimerButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.decreaseTimerButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.decreaseTimerButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.decreaseTimerButton.setIcon(icon1)
        self.decreaseTimerButton.setIconSize(QtCore.QSize(56, 56))
        self.decreaseTimerButton.setAutoDefault(False)
        self.decreaseTimerButton.setDefault(False)
        self.decreaseTimerButton.setFlat(True)
        self.decreaseTimerButton.setObjectName("decreaseTimerButton")
        self.verticalLayout1.addWidget(self.decreaseTimerButton)
        self.horizontalLayout7.addLayout(self.verticalLayout1)
        self.burnerLabel = QtWidgets.QLabel(self.controllerPage)
        self.burnerLabel.setGeometry(QtCore.QRect(920, 380, 54, 17))
        self.burnerLabel.setText("")
        self.burnerLabel.setObjectName("burnerLabel")
        self.thermostatFrame = QtWidgets.QFrame(self.controllerPage)
        self.thermostatFrame.setGeometry(QtCore.QRect(550, 420, 461, 141))
        self.thermostatFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.thermostatFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.thermostatFrame.setObjectName("thermostatFrame")
        self.thermostatLabel = QtWidgets.QLabel(self.thermostatFrame)
        self.thermostatLabel.setGeometry(QtCore.QRect(10, 0, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.thermostatLabel.setFont(font)
        self.thermostatLabel.setWordWrap(False)
        self.thermostatLabel.setObjectName("thermostatLabel")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.thermostatFrame)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 40, 441, 91))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout5.setObjectName("horizontalLayout5")
        self.decrementThermostatButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.decrementThermostatButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.decrementThermostatButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resources/thermostatDown.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.decrementThermostatButton.setIcon(icon2)
        self.decrementThermostatButton.setIconSize(QtCore.QSize(64, 64))
        self.decrementThermostatButton.setAutoRepeat(True)
        self.decrementThermostatButton.setAutoRepeatDelay(100)
        self.decrementThermostatButton.setAutoRepeatInterval(400)
        self.decrementThermostatButton.setAutoDefault(False)
        self.decrementThermostatButton.setDefault(False)
        self.decrementThermostatButton.setFlat(True)
        self.decrementThermostatButton.setObjectName("decrementThermostatButton")
        self.horizontalLayout5.addWidget(self.decrementThermostatButton)
        self.horizontalSlider = QtWidgets.QSlider(self.horizontalLayoutWidget_5)
        self.horizontalSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.horizontalSlider.setMinimum(100)
        self.horizontalSlider.setMaximum(550)
        self.horizontalSlider.setSingleStep(5)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setTickInterval(50)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout5.addWidget(self.horizontalSlider)
        self.incrementThermostatButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.incrementThermostatButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.incrementThermostatButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resources/thermostatUp.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.incrementThermostatButton.setIcon(icon3)
        self.incrementThermostatButton.setIconSize(QtCore.QSize(64, 64))
        self.incrementThermostatButton.setAutoRepeat(True)
        self.incrementThermostatButton.setAutoRepeatDelay(100)
        self.incrementThermostatButton.setAutoRepeatInterval(400)
        self.incrementThermostatButton.setAutoDefault(False)
        self.incrementThermostatButton.setDefault(False)
        self.incrementThermostatButton.setFlat(True)
        self.incrementThermostatButton.setObjectName("incrementThermostatButton")
        self.horizontalLayout5.addWidget(self.incrementThermostatButton)
        self.thermostatLCD = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thermostatLCD.sizePolicy().hasHeightForWidth())
        self.thermostatLCD.setSizePolicy(sizePolicy)
        self.thermostatLCD.setMinimumSize(QtCore.QSize(100, 0))
        self.thermostatLCD.setMaximumSize(QtCore.QSize(16777215, 60))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 1, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 1, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 157, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.thermostatLCD.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.thermostatLCD.setFont(font)
        self.thermostatLCD.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.thermostatLCD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.thermostatLCD.setDigitCount(3)
        self.thermostatLCD.setProperty("value", 100.0)
        self.thermostatLCD.setObjectName("thermostatLCD")
        self.horizontalLayout5.addWidget(self.thermostatLCD)
        self.thermostatDegreeLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(34)
        font.setBold(False)
        font.setWeight(50)
        self.thermostatDegreeLabel.setFont(font)
        self.thermostatDegreeLabel.setWordWrap(False)
        self.thermostatDegreeLabel.setObjectName("thermostatDegreeLabel")
        self.horizontalLayout5.addWidget(self.thermostatDegreeLabel)
        self.lightButton = QtWidgets.QPushButton(self.controllerPage)
        self.lightButton.setGeometry(QtCore.QRect(510, 230, 76, 70))
        self.lightButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lightButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/resources/lightOff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/resources/lightOn.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.lightButton.setIcon(icon4)
        self.lightButton.setIconSize(QtCore.QSize(64, 64))
        self.lightButton.setCheckable(True)
        self.lightButton.setAutoDefault(False)
        self.lightButton.setDefault(False)
        self.lightButton.setFlat(True)
        self.lightButton.setObjectName("lightButton")
        self.fanButton = QtWidgets.QPushButton(self.controllerPage)
        self.fanButton.setGeometry(QtCore.QRect(600, 230, 76, 70))
        self.fanButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fanButton.setText("")
        self.fanButton.setIconSize(QtCore.QSize(76, 76))
        self.fanButton.setCheckable(False)
        self.fanButton.setAutoDefault(False)
        self.fanButton.setDefault(False)
        self.fanButton.setFlat(True)
        self.fanButton.setObjectName("fanButton")
        self.burnerButton = QtWidgets.QPushButton(self.controllerPage)
        self.burnerButton.setGeometry(QtCore.QRect(420, 440, 111, 101))
        self.burnerButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.burnerButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/resources/OnOff.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.burnerButton.setIcon(icon5)
        self.burnerButton.setIconSize(QtCore.QSize(120, 120))
        self.burnerButton.setAutoDefault(False)
        self.burnerButton.setDefault(False)
        self.burnerButton.setFlat(True)
        self.burnerButton.setObjectName("burnerButton")
        self.steamButton = QtWidgets.QPushButton(self.controllerPage)
        self.steamButton.setGeometry(QtCore.QRect(510, 330, 76, 70))
        self.steamButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.steamButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/resources/steam.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.steamButton.setIcon(icon6)
        self.steamButton.setIconSize(QtCore.QSize(76, 76))
        self.steamButton.setCheckable(False)
        self.steamButton.setAutoDefault(False)
        self.steamButton.setDefault(False)
        self.steamButton.setFlat(True)
        self.steamButton.setObjectName("steamButton")
        self.burnerValveButton = QtWidgets.QPushButton(self.controllerPage)
        self.burnerValveButton.setGeometry(QtCore.QRect(600, 330, 76, 70))
        self.burnerValveButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.burnerValveButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/resources/burnerValveOff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/resources/burnerValveOn.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.burnerValveButton.setIcon(icon7)
        self.burnerValveButton.setIconSize(QtCore.QSize(70, 70))
        self.burnerValveButton.setCheckable(True)
        self.burnerValveButton.setAutoDefault(False)
        self.burnerValveButton.setDefault(False)
        self.burnerValveButton.setFlat(True)
        self.burnerValveButton.setObjectName("burnerValveButton")
        self.burnerValveLabel = QtWidgets.QLabel(self.controllerPage)
        self.burnerValveLabel.setGeometry(QtCore.QRect(820, 370, 54, 17))
        self.burnerValveLabel.setText("")
        self.burnerValveLabel.setObjectName("burnerValveLabel")
        self.internalOpeningButton = QtWidgets.QPushButton(self.controllerPage)
        self.internalOpeningButton.setGeometry(QtCore.QRect(420, 230, 84, 70))
        self.internalOpeningButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.internalOpeningButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/resources/internalOpeningOpen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/resources/internalOpeningClose.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.internalOpeningButton.setIcon(icon8)
        self.internalOpeningButton.setIconSize(QtCore.QSize(85, 85))
        self.internalOpeningButton.setCheckable(True)
        self.internalOpeningButton.setAutoDefault(False)
        self.internalOpeningButton.setDefault(False)
        self.internalOpeningButton.setFlat(True)
        self.internalOpeningButton.setObjectName("internalOpeningButton")
        self.externalOpeningButton = QtWidgets.QPushButton(self.controllerPage)
        self.externalOpeningButton.setGeometry(QtCore.QRect(420, 330, 84, 70))
        self.externalOpeningButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.externalOpeningButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/resources/externalOpeningOpen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":/resources/externalOpeningClose.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.externalOpeningButton.setIcon(icon9)
        self.externalOpeningButton.setIconSize(QtCore.QSize(76, 76))
        self.externalOpeningButton.setCheckable(True)
        self.externalOpeningButton.setAutoDefault(False)
        self.externalOpeningButton.setDefault(False)
        self.externalOpeningButton.setFlat(True)
        self.externalOpeningButton.setObjectName("externalOpeningButton")
        self.resistanceButton = QtWidgets.QPushButton(self.controllerPage)
        self.resistanceButton.setGeometry(QtCore.QRect(680, 330, 76, 70))
        self.resistanceButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.resistanceButton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/resources/resistanceOff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon10.addPixmap(QtGui.QPixmap(":/resources/resistanceOn.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.resistanceButton.setIcon(icon10)
        self.resistanceButton.setIconSize(QtCore.QSize(56, 56))
        self.resistanceButton.setCheckable(True)
        self.resistanceButton.setAutoDefault(False)
        self.resistanceButton.setDefault(False)
        self.resistanceButton.setFlat(True)
        self.resistanceButton.setObjectName("resistanceButton")
        self.rotisserieButton = QtWidgets.QPushButton(self.controllerPage)
        self.rotisserieButton.setGeometry(QtCore.QRect(680, 230, 76, 70))
        self.rotisserieButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.rotisserieButton.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/resources/rotisserieOff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon11.addPixmap(QtGui.QPixmap(":/resources/rotisserieOn.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.rotisserieButton.setIcon(icon11)
        self.rotisserieButton.setIconSize(QtCore.QSize(76, 76))
        self.rotisserieButton.setCheckable(True)
        self.rotisserieButton.setAutoDefault(False)
        self.rotisserieButton.setDefault(False)
        self.rotisserieButton.setFlat(True)
        self.rotisserieButton.setObjectName("rotisserieButton")
        self.vacuumButton = QtWidgets.QPushButton(self.controllerPage)
        self.vacuumButton.setGeometry(QtCore.QRect(770, 230, 76, 70))
        self.vacuumButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.vacuumButton.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/resources/vacuumOff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon12.addPixmap(QtGui.QPixmap(":/resources/vacuumOn.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.vacuumButton.setIcon(icon12)
        self.vacuumButton.setIconSize(QtCore.QSize(64, 64))
        self.vacuumButton.setCheckable(True)
        self.vacuumButton.setAutoDefault(False)
        self.vacuumButton.setDefault(False)
        self.vacuumButton.setFlat(True)
        self.vacuumButton.setObjectName("vacuumButton")
        self.temperaturesFrame = QtWidgets.QFrame(self.controllerPage)
        self.temperaturesFrame.setGeometry(QtCore.QRect(10, 10, 391, 371))
        self.temperaturesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.temperaturesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.temperaturesFrame.setObjectName("temperaturesFrame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.temperaturesFrame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.temperatureOvenLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.temperatureOvenLabel.setFont(font)
        self.temperatureOvenLabel.setWordWrap(False)
        self.temperatureOvenLabel.setObjectName("temperatureOvenLabel")
        self.horizontalLayout1.addWidget(self.temperatureOvenLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout1.addItem(spacerItem)
        self.ovenLCD = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ovenLCD.sizePolicy().hasHeightForWidth())
        self.ovenLCD.setSizePolicy(sizePolicy)
        self.ovenLCD.setMinimumSize(QtCore.QSize(85, 85))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ovenLCD.setFont(font)
        self.ovenLCD.setFrameShape(QtWidgets.QFrame.Box)
        self.ovenLCD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ovenLCD.setDigitCount(3)
        self.ovenLCD.setObjectName("ovenLCD")
        self.horizontalLayout1.addWidget(self.ovenLCD)
        self.degreeLabel1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.degreeLabel1.setFont(font)
        self.degreeLabel1.setWordWrap(False)
        self.degreeLabel1.setObjectName("degreeLabel1")
        self.horizontalLayout1.addWidget(self.degreeLabel1)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.temperaturesFrame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 180, 371, 91))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout3.setObjectName("horizontalLayout3")
        self.temperaturePufferLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.temperaturePufferLabel.setFont(font)
        self.temperaturePufferLabel.setWordWrap(False)
        self.temperaturePufferLabel.setObjectName("temperaturePufferLabel")
        self.horizontalLayout3.addWidget(self.temperaturePufferLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout3.addItem(spacerItem1)
        self.pufferLCD = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pufferLCD.sizePolicy().hasHeightForWidth())
        self.pufferLCD.setSizePolicy(sizePolicy)
        self.pufferLCD.setMinimumSize(QtCore.QSize(85, 85))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pufferLCD.setFont(font)
        self.pufferLCD.setFrameShape(QtWidgets.QFrame.Box)
        self.pufferLCD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pufferLCD.setDigitCount(3)
        self.pufferLCD.setObjectName("pufferLCD")
        self.horizontalLayout3.addWidget(self.pufferLCD)
        self.degreeLabel3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.degreeLabel3.setFont(font)
        self.degreeLabel3.setWordWrap(False)
        self.degreeLabel3.setObjectName("degreeLabel3")
        self.horizontalLayout3.addWidget(self.degreeLabel3)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.temperaturesFrame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 100, 371, 91))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.temperatureFloorLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.temperatureFloorLabel.setFont(font)
        self.temperatureFloorLabel.setWordWrap(False)
        self.temperatureFloorLabel.setObjectName("temperatureFloorLabel")
        self.horizontalLayout2.addWidget(self.temperatureFloorLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout2.addItem(spacerItem2)
        self.floorLCD = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.floorLCD.sizePolicy().hasHeightForWidth())
        self.floorLCD.setSizePolicy(sizePolicy)
        self.floorLCD.setMinimumSize(QtCore.QSize(85, 85))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.floorLCD.setFont(font)
        self.floorLCD.setFrameShape(QtWidgets.QFrame.Box)
        self.floorLCD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.floorLCD.setDigitCount(3)
        self.floorLCD.setObjectName("floorLCD")
        self.horizontalLayout2.addWidget(self.floorLCD)
        self.degreeLabel2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.degreeLabel2.setFont(font)
        self.degreeLabel2.setWordWrap(False)
        self.degreeLabel2.setObjectName("degreeLabel2")
        self.horizontalLayout2.addWidget(self.degreeLabel2)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.temperaturesFrame)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 270, 371, 91))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout4.setObjectName("horizontalLayout4")
        self.temperatureFumesLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.temperatureFumesLabel.setFont(font)
        self.temperatureFumesLabel.setWordWrap(False)
        self.temperatureFumesLabel.setObjectName("temperatureFumesLabel")
        self.horizontalLayout4.addWidget(self.temperatureFumesLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout4.addItem(spacerItem3)
        self.fumesLCD = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fumesLCD.sizePolicy().hasHeightForWidth())
        self.fumesLCD.setSizePolicy(sizePolicy)
        self.fumesLCD.setMinimumSize(QtCore.QSize(85, 85))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fumesLCD.setFont(font)
        self.fumesLCD.setFrameShape(QtWidgets.QFrame.Box)
        self.fumesLCD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fumesLCD.setDigitCount(3)
        self.fumesLCD.setObjectName("fumesLCD")
        self.horizontalLayout4.addWidget(self.fumesLCD)
        self.degreeLabel4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.degreeLabel4.setFont(font)
        self.degreeLabel4.setWordWrap(False)
        self.degreeLabel4.setObjectName("degreeLabel4")
        self.horizontalLayout4.addWidget(self.degreeLabel4)
        self.topFrame = QtWidgets.QFrame(self.controllerPage)
        self.topFrame.setGeometry(QtCore.QRect(410, 10, 431, 201))
        self.topFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topFrame.setObjectName("topFrame")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.topFrame)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 100, 411, 91))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout9.setObjectName("horizontalLayout9")
        self.gasLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.gasLabel.setFont(font)
        self.gasLabel.setWordWrap(False)
        self.gasLabel.setObjectName("gasLabel")
        self.horizontalLayout9.addWidget(self.gasLabel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout9.addItem(spacerItem4)
        self.gasLCD = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gasLCD.sizePolicy().hasHeightForWidth())
        self.gasLCD.setSizePolicy(sizePolicy)
        self.gasLCD.setMinimumSize(QtCore.QSize(85, 85))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.gasLCD.setFont(font)
        self.gasLCD.setFrameShape(QtWidgets.QFrame.Box)
        self.gasLCD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gasLCD.setDigitCount(4)
        self.gasLCD.setObjectName("gasLCD")
        self.horizontalLayout9.addWidget(self.gasLCD)
        self.PaLabel2 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.PaLabel2.setFont(font)
        self.PaLabel2.setWordWrap(False)
        self.PaLabel2.setObjectName("PaLabel2")
        self.horizontalLayout9.addWidget(self.PaLabel2)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.topFrame)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 411, 91))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout6.setObjectName("horizontalLayout6")
        self.pressionLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pressionLabel.setFont(font)
        self.pressionLabel.setWordWrap(False)
        self.pressionLabel.setObjectName("pressionLabel")
        self.horizontalLayout6.addWidget(self.pressionLabel)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout6.addItem(spacerItem5)
        self.pressionLCD = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pressionLCD.sizePolicy().hasHeightForWidth())
        self.pressionLCD.setSizePolicy(sizePolicy)
        self.pressionLCD.setMinimumSize(QtCore.QSize(85, 85))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pressionLCD.setFont(font)
        self.pressionLCD.setFrameShape(QtWidgets.QFrame.Box)
        self.pressionLCD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pressionLCD.setDigitCount(4)
        self.pressionLCD.setObjectName("pressionLCD")
        self.horizontalLayout6.addWidget(self.pressionLCD)
        self.PaLabel1 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.PaLabel1.setFont(font)
        self.PaLabel1.setWordWrap(False)
        self.PaLabel1.setObjectName("PaLabel1")
        self.horizontalLayout6.addWidget(self.PaLabel1)
        self.controller_settingsButton = QtWidgets.QPushButton(self.controllerPage)
        self.controller_settingsButton.setGeometry(QtCore.QRect(870, 70, 141, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.controller_settingsButton.setFont(font)
        self.controller_settingsButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.controller_settingsButton.setFlat(False)
        self.controller_settingsButton.setObjectName("controller_settingsButton")
        self.controller_chartsButton = QtWidgets.QPushButton(self.controllerPage)
        self.controller_chartsButton.setGeometry(QtCore.QRect(870, 120, 141, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.controller_chartsButton.setFont(font)
        self.controller_chartsButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.controller_chartsButton.setFlat(False)
        self.controller_chartsButton.setObjectName("controller_chartsButton")
        self.stackedWidget.addWidget(self.controllerPage)
        self.chartsPage = QtWidgets.QWidget()
        self.chartsPage.setObjectName("chartsPage")
        self.charts_controllerButton = QtWidgets.QPushButton(self.chartsPage)
        self.charts_controllerButton.setGeometry(QtCore.QRect(840, 10, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.charts_controllerButton.setFont(font)
        self.charts_controllerButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.charts_controllerButton.setFlat(False)
        self.charts_controllerButton.setObjectName("charts_controllerButton")
        self.charts_settingsButton = QtWidgets.QPushButton(self.chartsPage)
        self.charts_settingsButton.setGeometry(QtCore.QRect(840, 60, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.charts_settingsButton.setFont(font)
        self.charts_settingsButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.charts_settingsButton.setFlat(False)
        self.charts_settingsButton.setObjectName("charts_settingsButton")
        self.charts_realTimeButton = QtWidgets.QPushButton(self.chartsPage)
        self.charts_realTimeButton.setGeometry(QtCore.QRect(840, 360, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.charts_realTimeButton.setFont(font)
        self.charts_realTimeButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.charts_realTimeButton.setCheckable(True)
        self.charts_realTimeButton.setFlat(False)
        self.charts_realTimeButton.setObjectName("charts_realTimeButton")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.chartsPage)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 811, 551))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.chartsLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.chartsLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.chartsLayout.setContentsMargins(0, 0, 0, 0)
        self.chartsLayout.setObjectName("chartsLayout")
        self.charts_ovenSerieButton = QtWidgets.QPushButton(self.chartsPage)
        self.charts_ovenSerieButton.setGeometry(QtCore.QRect(840, 250, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.charts_ovenSerieButton.setFont(font)
        self.charts_ovenSerieButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.charts_ovenSerieButton.setCheckable(True)
        self.charts_ovenSerieButton.setChecked(True)
        self.charts_ovenSerieButton.setFlat(False)
        self.charts_ovenSerieButton.setObjectName("charts_ovenSerieButton")
        self.charts_floorSerieButton = QtWidgets.QPushButton(self.chartsPage)
        self.charts_floorSerieButton.setGeometry(QtCore.QRect(930, 250, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.charts_floorSerieButton.setFont(font)
        self.charts_floorSerieButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.charts_floorSerieButton.setCheckable(True)
        self.charts_floorSerieButton.setChecked(True)
        self.charts_floorSerieButton.setFlat(False)
        self.charts_floorSerieButton.setObjectName("charts_floorSerieButton")
        self.charts_pufferSerieButton = QtWidgets.QPushButton(self.chartsPage)
        self.charts_pufferSerieButton.setGeometry(QtCore.QRect(840, 300, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.charts_pufferSerieButton.setFont(font)
        self.charts_pufferSerieButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.charts_pufferSerieButton.setCheckable(True)
        self.charts_pufferSerieButton.setChecked(True)
        self.charts_pufferSerieButton.setFlat(False)
        self.charts_pufferSerieButton.setObjectName("charts_pufferSerieButton")
        self.charts_fumesSerieButton = QtWidgets.QPushButton(self.chartsPage)
        self.charts_fumesSerieButton.setGeometry(QtCore.QRect(930, 300, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.charts_fumesSerieButton.setFont(font)
        self.charts_fumesSerieButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.charts_fumesSerieButton.setCheckable(True)
        self.charts_fumesSerieButton.setChecked(True)
        self.charts_fumesSerieButton.setFlat(False)
        self.charts_fumesSerieButton.setObjectName("charts_fumesSerieButton")
        self.line_4 = QtWidgets.QFrame(self.chartsPage)
        self.line_4.setGeometry(QtCore.QRect(840, 350, 171, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.chartsPage)
        self.line_5.setGeometry(QtCore.QRect(840, 410, 171, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.charts_lastHourButton = QtWidgets.QPushButton(self.chartsPage)
        self.charts_lastHourButton.setGeometry(QtCore.QRect(840, 420, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.charts_lastHourButton.setFont(font)
        self.charts_lastHourButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.charts_lastHourButton.setCheckable(True)
        self.charts_lastHourButton.setFlat(False)
        self.charts_lastHourButton.setObjectName("charts_lastHourButton")
        self.charts_lastDayButton = QtWidgets.QPushButton(self.chartsPage)
        self.charts_lastDayButton.setGeometry(QtCore.QRect(840, 470, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.charts_lastDayButton.setFont(font)
        self.charts_lastDayButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.charts_lastDayButton.setCheckable(True)
        self.charts_lastDayButton.setFlat(False)
        self.charts_lastDayButton.setObjectName("charts_lastDayButton")
        self.charts_lastWeekButton = QtWidgets.QPushButton(self.chartsPage)
        self.charts_lastWeekButton.setGeometry(QtCore.QRect(840, 520, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.charts_lastWeekButton.setFont(font)
        self.charts_lastWeekButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.charts_lastWeekButton.setCheckable(True)
        self.charts_lastWeekButton.setChecked(False)
        self.charts_lastWeekButton.setFlat(False)
        self.charts_lastWeekButton.setObjectName("charts_lastWeekButton")
        self.stackedWidget.addWidget(self.chartsPage)
        self.settingsPage = QtWidgets.QWidget()
        self.settingsPage.setObjectName("settingsPage")
        self.alexaButton = QtWidgets.QPushButton(self.settingsPage)
        self.alexaButton.setGeometry(QtCore.QRect(40, 460, 76, 70))
        self.alexaButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.alexaButton.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/resources/alexaOff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon13.addPixmap(QtGui.QPixmap(":/resources/alexaOn.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.alexaButton.setIcon(icon13)
        self.alexaButton.setIconSize(QtCore.QSize(64, 64))
        self.alexaButton.setCheckable(True)
        self.alexaButton.setAutoDefault(False)
        self.alexaButton.setDefault(False)
        self.alexaButton.setFlat(True)
        self.alexaButton.setObjectName("alexaButton")
        self.quitButton = QtWidgets.QPushButton(self.settingsPage)
        self.quitButton.setGeometry(QtCore.QRect(930, 20, 81, 81))
        self.quitButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.quitButton.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/resources/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.quitButton.setIcon(icon14)
        self.quitButton.setIconSize(QtCore.QSize(100, 100))
        self.quitButton.setCheckable(False)
        self.quitButton.setAutoDefault(False)
        self.quitButton.setDefault(False)
        self.quitButton.setFlat(True)
        self.quitButton.setObjectName("quitButton")
        self.settings_chartsButton = QtWidgets.QPushButton(self.settingsPage)
        self.settings_chartsButton.setGeometry(QtCore.QRect(210, 20, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.settings_chartsButton.setFont(font)
        self.settings_chartsButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.settings_chartsButton.setFlat(False)
        self.settings_chartsButton.setObjectName("settings_chartsButton")
        self.settings_controllerButton = QtWidgets.QPushButton(self.settingsPage)
        self.settings_controllerButton.setGeometry(QtCore.QRect(20, 20, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.settings_controllerButton.setFont(font)
        self.settings_controllerButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.settings_controllerButton.setFlat(False)
        self.settings_controllerButton.setObjectName("settings_controllerButton")
        self.formLayoutWidget = QtWidgets.QWidget(self.settingsPage)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 70, 561, 294))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.settingsLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.settingsLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.settingsLayout.setContentsMargins(0, 0, 0, 0)
        self.settingsLayout.setHorizontalSpacing(20)
        self.settingsLayout.setVerticalSpacing(10)
        self.settingsLayout.setObjectName("settingsLayout")
        self.pressionCheckLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pressionCheckLabel.setFont(font)
        self.pressionCheckLabel.setWordWrap(False)
        self.pressionCheckLabel.setObjectName("pressionCheckLabel")
        self.settingsLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pressionCheckLabel)
        self.pressionThresholdLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pressionThresholdLabel.setFont(font)
        self.pressionThresholdLabel.setWordWrap(False)
        self.pressionThresholdLabel.setObjectName("pressionThresholdLabel")
        self.settingsLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pressionThresholdLabel)
        self.internalOpeningTimeLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.internalOpeningTimeLabel.setFont(font)
        self.internalOpeningTimeLabel.setWordWrap(False)
        self.internalOpeningTimeLabel.setObjectName("internalOpeningTimeLabel")
        self.settingsLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.internalOpeningTimeLabel)
        self.upperCheckerTimeLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.upperCheckerTimeLabel.setFont(font)
        self.upperCheckerTimeLabel.setWordWrap(False)
        self.upperCheckerTimeLabel.setObjectName("upperCheckerTimeLabel")
        self.settingsLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.upperCheckerTimeLabel)
        self.valveThresholdLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.valveThresholdLabel.setFont(font)
        self.valveThresholdLabel.setWordWrap(False)
        self.valveThresholdLabel.setObjectName("valveThresholdLabel")
        self.settingsLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.valveThresholdLabel)
        self.persistDataLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.persistDataLabel.setFont(font)
        self.persistDataLabel.setWordWrap(False)
        self.persistDataLabel.setObjectName("persistDataLabel")
        self.settingsLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.persistDataLabel)
        self.keypadFrame = QtWidgets.QFrame(self.settingsPage)
        self.keypadFrame.setGeometry(QtCore.QRect(680, 250, 301, 281))
        self.keypadFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.keypadFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.keypadFrame.setObjectName("keypadFrame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.keypadFrame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 281, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.keypadLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.keypadLayout.setContentsMargins(0, 0, 0, 0)
        self.keypadLayout.setObjectName("keypadLayout")
        self.button6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button6.sizePolicy().hasHeightForWidth())
        self.button6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.button6.setFont(font)
        self.button6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button6.setFlat(False)
        self.button6.setObjectName("button6")
        self.keypadLayout.addWidget(self.button6, 1, 2, 1, 1)
        self.button9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button9.sizePolicy().hasHeightForWidth())
        self.button9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.button9.setFont(font)
        self.button9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button9.setFlat(False)
        self.button9.setObjectName("button9")
        self.keypadLayout.addWidget(self.button9, 0, 2, 1, 1)
        self.button7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button7.sizePolicy().hasHeightForWidth())
        self.button7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.button7.setFont(font)
        self.button7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button7.setFlat(False)
        self.button7.setObjectName("button7")
        self.keypadLayout.addWidget(self.button7, 0, 0, 1, 1)
        self.button1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button1.sizePolicy().hasHeightForWidth())
        self.button1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.button1.setFont(font)
        self.button1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button1.setFlat(False)
        self.button1.setObjectName("button1")
        self.keypadLayout.addWidget(self.button1, 2, 0, 1, 1)
        self.button4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button4.sizePolicy().hasHeightForWidth())
        self.button4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.button4.setFont(font)
        self.button4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button4.setFlat(False)
        self.button4.setObjectName("button4")
        self.keypadLayout.addWidget(self.button4, 1, 0, 1, 1)
        self.button8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button8.sizePolicy().hasHeightForWidth())
        self.button8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.button8.setFont(font)
        self.button8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button8.setFlat(False)
        self.button8.setObjectName("button8")
        self.keypadLayout.addWidget(self.button8, 0, 1, 1, 1)
        self.button3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button3.sizePolicy().hasHeightForWidth())
        self.button3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.button3.setFont(font)
        self.button3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button3.setFlat(False)
        self.button3.setObjectName("button3")
        self.keypadLayout.addWidget(self.button3, 2, 2, 1, 1)
        self.button2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button2.sizePolicy().hasHeightForWidth())
        self.button2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.button2.setFont(font)
        self.button2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button2.setFlat(False)
        self.button2.setObjectName("button2")
        self.keypadLayout.addWidget(self.button2, 2, 1, 1, 1)
        self.button5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button5.sizePolicy().hasHeightForWidth())
        self.button5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.button5.setFont(font)
        self.button5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button5.setFlat(False)
        self.button5.setObjectName("button5")
        self.keypadLayout.addWidget(self.button5, 1, 1, 1, 1)
        self.buttonDel = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDel.sizePolicy().hasHeightForWidth())
        self.buttonDel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.buttonDel.setFont(font)
        self.buttonDel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonDel.setFlat(False)
        self.buttonDel.setObjectName("buttonDel")
        self.keypadLayout.addWidget(self.buttonDel, 3, 0, 1, 1)
        self.button0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button0.sizePolicy().hasHeightForWidth())
        self.button0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.button0.setFont(font)
        self.button0.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button0.setFlat(False)
        self.button0.setObjectName("button0")
        self.keypadLayout.addWidget(self.button0, 3, 1, 1, 1)
        self.buttonOk = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonOk.sizePolicy().hasHeightForWidth())
        self.buttonOk.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.buttonOk.setFont(font)
        self.buttonOk.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonOk.setFlat(False)
        self.buttonOk.setObjectName("buttonOk")
        self.keypadLayout.addWidget(self.buttonOk, 3, 2, 1, 1)
        self.stackedWidget.addWidget(self.settingsPage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.horizontalSlider.valueChanged['int'].connect(self.thermostatLCD.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gestione Forno"))
        self.startTimerButton.setText(_translate("MainWindow", "Avvia"))
        self.stopTimerButton.setText(_translate("MainWindow", "Ferma"))
        self.resetTimerButton.setText(_translate("MainWindow", "Reset"))
        self.thermostatLabel.setText(_translate("MainWindow", "Imposta temperatura"))
        self.thermostatDegreeLabel.setText(_translate("MainWindow", "°C"))
        self.temperatureOvenLabel.setText(_translate("MainWindow", "Sonda forno"))
        self.degreeLabel1.setText(_translate("MainWindow", "°C"))
        self.temperaturePufferLabel.setText(_translate("MainWindow", "Sonda puffer"))
        self.degreeLabel3.setText(_translate("MainWindow", "°C"))
        self.temperatureFloorLabel.setText(_translate("MainWindow", "Sonda platea"))
        self.degreeLabel2.setText(_translate("MainWindow", "°C"))
        self.temperatureFumesLabel.setText(_translate("MainWindow", "Sonda fumi"))
        self.degreeLabel4.setText(_translate("MainWindow", "°C"))
        self.gasLabel.setText(_translate("MainWindow", "Pressione gas"))
        self.PaLabel2.setText(_translate("MainWindow", "Pa"))
        self.pressionLabel.setText(_translate("MainWindow", "Pressione forno"))
        self.PaLabel1.setText(_translate("MainWindow", "Pa"))
        self.controller_settingsButton.setText(_translate("MainWindow", "Impostazioni"))
        self.controller_chartsButton.setText(_translate("MainWindow", "Grafici"))
        self.charts_controllerButton.setText(_translate("MainWindow", "Controller"))
        self.charts_settingsButton.setText(_translate("MainWindow", "Impostazioni"))
        self.charts_realTimeButton.setText(_translate("MainWindow", "Tempo reale"))
        self.charts_ovenSerieButton.setText(_translate("MainWindow", "Forno"))
        self.charts_floorSerieButton.setText(_translate("MainWindow", "Platea"))
        self.charts_pufferSerieButton.setText(_translate("MainWindow", "Puffer"))
        self.charts_fumesSerieButton.setText(_translate("MainWindow", "Fumi"))
        self.charts_lastHourButton.setText(_translate("MainWindow", "Ultima ora"))
        self.charts_lastDayButton.setText(_translate("MainWindow", "Ultimo giorno"))
        self.charts_lastWeekButton.setText(_translate("MainWindow", "Ultima settimana"))
        self.settings_chartsButton.setText(_translate("MainWindow", "Grafici"))
        self.settings_controllerButton.setText(_translate("MainWindow", "Controller"))
        self.pressionCheckLabel.setText(_translate("MainWindow", "Controllo pressione"))
        self.pressionThresholdLabel.setText(_translate("MainWindow", "Soglia pressione minima (Pa)"))
        self.internalOpeningTimeLabel.setText(_translate("MainWindow", "Tempo apertura interna (sec)"))
        self.upperCheckerTimeLabel.setText(_translate("MainWindow", "Tempo controllo temperatura (sec)"))
        self.valveThresholdLabel.setText(_translate("MainWindow", "Soglia chiusura valvola 2° fiamma(°C)"))
        self.persistDataLabel.setText(_translate("MainWindow", "Misurazioni persistite"))
        self.button6.setText(_translate("MainWindow", "6"))
        self.button9.setText(_translate("MainWindow", "9"))
        self.button7.setText(_translate("MainWindow", "7"))
        self.button1.setText(_translate("MainWindow", "1"))
        self.button4.setText(_translate("MainWindow", "4"))
        self.button8.setText(_translate("MainWindow", "8"))
        self.button3.setText(_translate("MainWindow", "3"))
        self.button2.setText(_translate("MainWindow", "2"))
        self.button5.setText(_translate("MainWindow", "5"))
        self.buttonDel.setText(_translate("MainWindow", "<"))
        self.button0.setText(_translate("MainWindow", "0"))
        self.buttonOk.setText(_translate("MainWindow", "OK"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

